# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Jekyll Bootstrap-3
tagline: Site Tagline
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username