baseurl: ""
title: nagu.io
tagline: Envision. Execute.
name: Nicolas Aguirre
email: nic.jsb (at) gmail (dot) com
github: novonagu
twitter: novonagu

exclude:
  - package.json
  - gulpfile.js
#gems:
#- jekyll-autoprefixer